### ISSUE TITLE
Conflict between fp16 and deterministic sampling

### ISSUE THREAD

**Issue by TimotheeMickus** [Helsinki-NLP/mammoth#71]
Encountered while training models in a multi-node setting (+ validation iter +  early stopping):

```
Traceback (most recent call last):
  File "/scratch/project_2005099/data/god-save-the-king/redo/mammoth/mammoth/distributed/communication.py", line 235, in consumer
    process_fn(
  File "/scratch/project_2005099/data/god-save-the-king/redo/mammoth/mammoth/train_single.py", line 168, in main
    trainer.train(
  File "/scratch/project_2005099/data/god-save-the-king/redo/mammoth/mammoth/trainer.py", line 293, in train
    self.optim.externally_managed_step(gradient_syncs)
  File "/scratch/project_2005099/data/god-save-the-king/redo/mammoth/mammoth/utils/optimizers.py", line 413, in externally_managed_step
    self._scaler.step(self._optimizer)
  File "/usr/local/lib64/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 452, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/usr/local/lib64/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 350, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
AttributeError: 'MultipleOptimizer' object has no attribute 'step'
```

@Waino seems related to #8 and #66 ?

**Comment by Waino** [comment]
Indeed. Due to the removal of the grad hook, `MultipleOptimizer` no longer has a method `step`, it has been replaced with `externally_managed_step` which takes information about which optimizers need to be stepped. This means that it is no longer compatible with `torch.cuda.amp.GradScaler`.

We may have to move the GradScaler inside of MultipleOptimizer, to wrap each sub-optimizer individually.

As a workaround, not using fp16/amp still works.
